#pragma config(Motor,  port2,           mLift,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mLeft,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mRight,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          mBucket,       tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

task autonomous()
{
	AutonomousCodePlaceholderForTesting();
}

task drive(){
	while(true){	
		motor[mLeft]  = (vexRT[Ch2] + vexRT[Ch1])* 0.8;  // (y + x)/2
		motor[mRight] = (vexRT[Ch2] - vexRT[Ch1])* 0.8;  // (y - x)/2
	}
}

task usercontrol()
{
	startTask(drive);
	while (true)
	{
//	if(vexRT[Ch3] > deadband) { if positive loop keep power on to hold lift	
		motor[mLift] = vexRT(Ch3) * 0.8;


		if(vexRT(Btn5D) == 1 || vexRT(Btn5U) ==1){
			motor[mBucket] = 50;
			wait1Msec(200);
			motor[mBucket] = 10;
		}
		else if(vexRT(Btn6D) == 1 || vexRT(Btn6U) ==1){
			motor[mBucket] = -50;
			wait1Msec(200);
			motor[mBucket] = 10;
		}
		else if(abs(vexRT[Ch2] + vexRT[Ch1])>15){
			motor[mBucket] = 10;  // (y - x)/2
		}
		else{
			motor[mBucket] = 0;  // (y - x)/2
		}
	}
}
