#pragma config(Motor,  port2,           mLeft,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           mRight,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           mArm,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mLift,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           mClaw,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void pre_auton()
{
	bStopTasksBetweenModes = true;
}

void moveClaw(int x){

}

task autonomous()
{
	AutonomousCodePlaceholderForTesting();
	 //++++++++ CODE TEXT OK TO HERE
	/*
	 // STACK HIGH CONE
	//close claw - keeping power to close
	//lift arm 
	//drive to stack
	//lower cone
	//open claw
	//back away
	
	//MOBILE GOAL
	//lift & hold claw 
	//lower MG lift 
	//drive to MG
	//lift MG
	//???  position MG to drive into corner  ???
	//drive into corner
	//lower MB
	//back out fast!*/
}

int deadBand = 15;
int armPower = 0;

task drive(){
	while(true){
		if(abs(vexRT[Ch2] + vexRT[Ch1]) > deadBand){
			motor[mLeft]  = (vexRT[Ch2] + vexRT[Ch1])* 0.8;  // (y + x)/2
			motor[mRight] = (vexRT[Ch2] - vexRT[Ch1])* 0.8;  // (y - x)/2
		}
		else {	//shut off motors
			motor[mLeft]  = 0;
			motor[mRight] = 0;
		}//end if
	}//end while
}//end task drive

task usercontrol()
{
	startTask(drive);

	while(true){
		if(vexRT(Btn7R) == 1 || vexRT(Btn8R) ==1){ //close claw
			motor[mClaw] = 50;
			wait1Msec(200);
			motor[mClaw] = 10;
		}
		else if(vexRT(Btn7L) == 1 || vexRT(Btn8L) ==1){ //open claw
			motor[mClaw] = -50;
			wait1Msec(200);
			motor[mClaw] = 0;
		}

		if(vexRT(Btn7U) == 1 || vexRT(Btn8U) ==1){ //raise lift
			motor[mLift] = 80;
			wait1Msec(350);
			motor[mLift] = 0;
		}
		else if(vexRT(Btn7D) == 1 || vexRT(Btn8D) ==1){ //lower lift
			motor[mLift] = -80;
			wait1Msec(350);
			motor[mLift] = 0;
		}

		if(vexRT[Ch3] > deadBand){ //claw arm 
			motor[mArm] = vexRT[Ch3]*0.5;
			armPower = 10;
		}
		else if(vexRT[Ch3]<deadBand *-1){
			motor[mArm]=vexRT[Ch3]*0.5;
			armPower = 0;
		}
		else{
			motor[mArm]=armPower;
		}
	}//end while
}//end user control
